import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.getBoj.useQuery();

  return (
    <>
      <Head>
        <title>Algorithm Study</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Algorithm Study</h1>
        <p>{JSON.stringify(hello.data, null, 2)}</p>
      </div>
    </>
  );
};

export default Home;
